title: le temps figé
description: >- 
   iu marimo
baseurl: "/"
url: "https://laviediu.github.io"
github_username:  laviediu

markdown: kramdown

plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"
hide_credits: true
hide_search: true
future: true

